# Imports
import streamlit as st
import pandas as pd
import pickle

# Load Model
model = pickle.load(open("models/extended_model.pkl", "rb"))

# Page Config
st.set_page_config(
    page_title="House Price Predictor",
    page_icon="🏠",
    layout="centered"
)

# Title and Description
st.title("🏠 House Price Prediction")

st.write("""
Predict house prices using a Linear Regression Model trained on:
- Property size
- House quality
- Neighborhood
- Garage capacity
- Basement area
- Year built
- Lot size
""")

st.divider()

# User Inputs
gr_liv_area = st.number_input(
    "Above Ground Living Area (sq ft)",
    min_value=300,
    max_value=6000,
    value=1500
)

bedrooms = st.number_input(
    "Number of Bedrooms",
    min_value=0,
    max_value=10,
    value=3
)

full_bath = st.number_input(
    "Number of Full Bathrooms",
    min_value=0,
    max_value=5,
    value=2
)

overall_qual = st.slider(
    "Overall Quality (1-10)",
    min_value=1,
    max_value=10,
    value=5
)

garage_cars = st.number_input(
    "Garage Capacity (Cars)",
    min_value=0,
    max_value=5,
    value=2
)

total_bsmt_sf = st.number_input(
    "Total Basement Area (sq ft)",
    min_value=0,
    max_value=6000,
    value=800
)

year_built = st.number_input(
    "Year Built",
    min_value=1800,
    max_value=2025,
    value=2000
)

lot_area = st.number_input(
    "Lot Area (sq ft)",
    min_value=1000,
    max_value=250000,
    value=8000
)

# Neighborhood Dropdown
neighborhoods = [
    'Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr',
    'CollgCr', 'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR',
    'MeadowV', 'Mitchel', 'NAmes', 'NPkVill', 'NWAmes',
    'NoRidge', 'NridgHt', 'OldTown', 'SWISU', 'Sawyer',
    'SawyerW', 'Somerst', 'StoneBr', 'Timber', 'Veenker'
]

selected_neighborhood = st.selectbox(
    "Neighborhood",
    neighborhoods
)

st.divider()

# Prediction
if st.button("Predict House Price"):

    input_data = {
        'GrLivArea': gr_liv_area,
        'BedroomAbvGr': bedrooms,
        'FullBath': full_bath,
        'OverallQual': overall_qual,
        'GarageCars': garage_cars,
        'TotalBsmtSF': total_bsmt_sf,
        'YearBuilt': year_built,
        'LotArea': lot_area
    }

    for neighborhood in neighborhoods:
        input_data[f'Neighborhood_{neighborhood}'] = 0

    selected_column = f'Neighborhood_{selected_neighborhood}'

    if selected_column in input_data:
        input_data[selected_column] = 1

    input_df = pd.DataFrame([input_data])

    model_features = model.feature_names_in_

    for col in model_features:
        if col not in input_df.columns:
            input_df[col] = 0

    input_df = input_df[model_features]

    prediction = model.predict(input_df)[0]

    st.success(
        f"Estimated House Price: ${prediction:,.2f}"
    )

    st.warning(
        "Note: Predictions are estimates generated by a machine learning model and may not be 100% accurate."
    )